- repo: sbdchd/neoformat
- repo: ntpeters/vim-better-whitespace
- repo: terryma/vim-multiple-cursors
- repo: tpope/vim-repeat
- repo: jszakmeister/vim-togglecursor
# - repo: rking/ag.vim
- repo: mhinz/vim-startify
- repo: rykka/riv.vim
- repo: tpope/vim-fugitive
- repo: tpope/vim-abolish
- repo: tpope/vim-projectionist
- repo: junegunn/gv.vim    # git commit browser
- repo: vim-scripts/BufOnly.vim
- repo: godlygeek/tabular
# - repo: kien/rainbow_parentheses.vim
- repo: ctrlpvim/ctrlp.vim
- repo: haya14busa/incsearch.vim
- repo: haya14busa/incsearch-fuzzy.vim
- repo: vim-airline/vim-airline
- repo: vim-airline/vim-airline-themes
- repo: tpope/vim-surround
- repo: junegunn/vim-easy-align
- repo: Valloric/MatchTagAlways

- repo: Yggdroot/indentLine
  hook_add: |
    let g:indentLine_bufNameExclude = ['NERD_tree.*', 'defx', 'startify', '__vista__']
    let g:indentLine_fileTypeExclude = ['defx', '__vista__']

# tencent jce file
- { repo: tenfyzhong/jce-highlight, on_ft: jce}

# pip install https://github.com/Rykka/instant-rst.py/archive/master.zip
- { repo: Rykka/InstantRst, on_ft: rst}
- { repo: PegasusWang/RST-Tables, on_ft: rst}
- { repo: iamcco/mathjax-support-for-mkdp, on_ft: markdown}

- repo: iamcco/markdown-preview.nvim
  on_ft: [ markdown, pandoc.markdown, rmd ]
  build: cd app & npm install

# Python related, NOTE python-mode use submodule
# cd ~/.cache/vim/dein/repos/github.com; mkdir python-mode
# git clone --recurse-submodules https://github.com/python-mode/python-mode
- { repo: python-mode/python-mode, on_ft: python}


- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to â†’ '
    let g:EasyMotion_keys = 'fjdksweoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1

# enable ycm if you write cpp
# - repo: Valloric/YouCompleteMe
#   build: ./install.py --clang-completer
